### PR TITLE
Make VAL enum values follow Cocoa conventions

### PR DESCRIPTION
**Pull request by dfed**
cc @mthole @EricMuller22 @stephencelis 

Bumping the pod spec version to 1.1 since this is a breaking change. Thoughts appreciated!

### CODE REVIEW

**Comment by stephencelis** [comment]
If the breaking change is an issue (minor version bumps usually ensure backwards compatibility), maybe the old enum values should still be available?

``` objective-c
 typedef NS_ENUM(NSUInteger, VALAccessibility) {
    VALAccessibilityWhenUnlocked = 1,
    VALAccessibilityAfterFirstUnlock,
    VALAccessibilityAlways,
    VALAccessibilityWhenPasscodeSetThisDeviceOnly __OSX_AVAILABLE_STARTING(__MAC_10_10,     VALAccessibleWhenUnlockedThisDeviceOnly,
    VALAccessibilityWhenUnlockedThisDeviceOnly,
    VALAccessibilityAfterFirstUnlockThisDeviceOnly,
    VALAccessibilityAlwaysThisDeviceOnly,

    VALAccessibleWhenUnlocked = VALAccessibilityWhenUnlocked,
    VALAccessibleAfterFirstUnlock,
    VALAccessibleAlways,
    VALAccessibleWhenPasscodeSetThisDeviceOnly __OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0),
    VALAccessibleAfterFirstUnlockThisDeviceOnly,
    VALAccessibleAlwaysThisDeviceOnly,
 };
```

**Comment by EricMuller22** [comment]
I think our internal consumers at Square are ok with a breaking change (and this project is nascent enough that I'm inclined to be ok with ripping the Band-Aid off quickly). We'll follow a more proper deprecation schedule from here on out.

**Comment by shawnwelch** [comment]
LGTM

**Comment by pwesten** [comment]
I'd merge without the __deprecated versions, especially this early on!

**Comment by dfed** [comment]
Looks like we've got a consensus here. Merging as-is. As Eric said, we will be better about breaking changes going forward.

 Thanks for raising the issue @stephencelis!

**Pull request merged**
