### PR TITLE
Make canAccessKeychain not crash on Mac

### PR DESCRIPTION
**Pull request by dfed**
cc @EricMuller22 @mikelikespie

### CODE REVIEW

**Comment by dfed** [comment]
Ignore CI. Working on that here: https://github.com/square/Valet/pull/5

**Comment by EricMuller22** [comment]
Gorm

**Comment by kyleve** [comment]
Should this have tests to avoid regressions?

**Comment by dfed** [comment]
There is a test, that's how I found the issue. @kyleve check out PR #5. Working on making running tests for both platforms automated.

**Comment by kyleve** [comment]
@dfed Excellent!

**Pull request merged**
