### PR TITLE
Transition CI builds over to GitHub Actions

### PR DESCRIPTION
**Pull request by NickEntin**
Travis CI [no longer has free macOS builds](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), so it's time to migrate away. This moves our CI builds over to GitHub Actions.

### CODE REVIEW

**Comment by NickEntin** [comment]
@dfed It looks like the macOS tests are failing due to missing entitlements. Any idea why this would have worked on Travis CI but not GitHub Actions? It should be running exactly the same commands, so presumably there's something different between the two environments?

**Comment by dfed** [comment]
@NickEntin welp. Let's dig in.

Looking at one example `test_setStringForKey_neutralizesMacOSAccessControlListVuln`:
* It's failing in CI
* I'm not seeing a `guard testEnvironmentIsSigned()` in there, so we didn't expect it to fail in CI
* I do see that it fails when I run it locally on my M1 Mac using 12.4 without going through the code-signing dance

I vaguely remember macOS 10.15 introducing changes that meant I _had_ to code-sign the environment in order for macOS tests to run. Our [`xcode11.3` machine on Travis was running macOS 10.14.6](https://docs.travis-ci.com/user/reference/osx/), and our new build is [on macOS 10.15](https://github.com/square/Valet/pull/256/checks?check_run_id=2211470405#step:1:7).

So, with all the above info, I think we hit the macOS Catalina time-bomb. I _hate_ to say it, but we should probably just delete the macOS tests from CI all-together. Speaking of which... I need to land #260 so folk know how on earth to test macOS.

**Comment by NickEntin** [comment]
Oh boo, turns out GitHub Actions doesn't actually support macOS 10.14, even though the virtual environments repo shows a specification for it. 😞 It silently uses macOS 10.15 instead.

Screen Shot 2021-06-08 at 10 50 10 PM

Screen Shot 2021-06-08 at 10 49 31 PM

There goes my workaround for testing macOS and running legacy iOS tests.

**Comment by NickEntin** [comment]
I'm not thrilled with what this does to our test matrix, but I think it's good enough for now and unblocks our CI.

**Xcode Build and Test**

Platform | Before | After
------------ | ------------- | -------------
iOS | 10, 11, 12, 13 | 12, 13, 14
tvOS | 10, 11, 12, 13 | 12, 13, 14
watchOS | 3, 4, 5, 6 | 5, 6, 7
macOS | 10.15 | 

**Swift Package Manager Build**

Platform | Before | After
------------ | ------------- | -------------
iOS | 13 | 13, 14
tvOS | 13 | 13, 14
watchOS | 6 | 6, 7
macOS | 10.15 | 10.15

**Comment by NickEntin** [comment]
```
Test Case '-[Valet_tvOS_Tests.SinglePromptSecureEnclaveIntegrationTests test_allKeys_doesNotReflectValetImplementationDetails]' started.
2021-06-10 23:32:12.171511+0000 Valet tvOS Test Host App[2434:43850] [Client,SPI,LAContext] externalizedContext on LAContext[2434:1] cid:2 returned 0
/Users/runner/work/Valet/Valet/Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift:119: error: -[Valet_tvOS_Tests.SinglePromptSecureEnclaveIntegrationTests test_allKeys_doesNotReflectValetImplementationDetails] : XCTAssertEqual failed: threw error "KeychainError.couldNotAccessKeychain"
Test Case '-[Valet_tvOS_Tests.SinglePromptSecureEnclaveIntegrationTests test_allKeys_doesNotReflectValetImplementationDetails]' failed (0.291 seconds).
Test Case '-[Valet_tvOS_Tests.SinglePromptSecureEnclaveIntegrationTests test_allKeys]' started.
2021-06-10 23:32:12.461466+0000 Valet tvOS Test Host App[2434:43850] [Client,SPI,LAContext] externalizedContext on LAContext[2434:1] cid:3 returned 0
/Users/runner/work/Valet/Valet/Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift:97: error: -[Valet_tvOS_Tests.SinglePromptSecureEnclaveIntegrationTests test_allKeys] : XCTAssertEqual failed: threw error "KeychainError.couldNotAccessKeychain"
2021-06-10 23:32:12.503067+0000 Valet tvOS Test Host App[2434:43850] [Client,SPI,LAContext] externalizedContext on LAContext[2434:1] cid:4 returned 0
/Users/runner/work/Valet/Valet/Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift:100: error: -[Valet_tvOS_Tests.SinglePromptSecureEnclaveIntegrationTests test_allKeys] : XCTAssertEqual failed: threw error "KeychainError.couldNotAccessKeychain"
2021-06-10 23:32:12.507018+0000 Valet tvOS Test Host App[2434:43850] [Client,SPI,LAContext] externalizedContext on LAContext[2434:1] cid:5 returned 0
/Users/runner/work/Valet/Valet/Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift:103: error: -[Valet_tvOS_Tests.SinglePromptSecureEnclaveIntegrationTests test_allKeys] : XCTAssertEqual failed: threw error "KeychainError.couldNotAccessKeychain"
2021-06-10 23:32:12.511302+0000 Valet tvOS Test Host App[2434:43850] [Client,SPI,LAContext] externalizedContext on LAContext[2434:1] cid:6 returned 0
/Users/runner/work/Valet/Valet/Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift:106: error: -[Valet_tvOS_Tests.SinglePromptSecureEnclaveIntegrationTests test_allKeys] : XCTAssertEqual failed: threw error "KeychainError.couldNotAccessKeychain"
Test Case '-[Valet_tvOS_Tests.SinglePromptSecureEnclaveIntegrationTests test_allKeys]' failed (0.065 seconds).
```

🤔  Not sure why these can't access the keychain on tvOS 14.

cc @allisonmoyer this is the same test class you were looking at in #268

**Comment by NickEntin** [comment]
Hmm, we're getting back a `-26276` error code in the tvOS tests, which doesn't match any of the `OSStatus` codes. Not sure how to debug this one.

**Comment by NickEntin** [comment]
The tvOS test failures are reproducing locally, so I think it's a separate bug in our test (filed #270 to track this). Removing tvOS 14 from our test matrix for now.

**Review by allisonmoyer — APPROVED** [review]

**Review by dfed — APPROVED** [review]
LGTM! Thanks for taking this on.

**Pull request merged**
